name: IntegrationTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.26.1'

    - name: Configure
      working-directory: ${{env.BUILD_DIR}}/integration_tests/cpm
      run: |
        mkdir "${{env.BUILD_DIR}}"
        cd "${{env.BUILD_DIR}}"
        cmake ..
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}/integration_tests/cpm
      run: |
        cmake --build . --config Debug
      shell: cmd
